Add header file checks for the libtiff and libgeotiff (instead of just library ones)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3946,7 +3946,145 @@ fi
 
 
 #### libtiff check ####
-echo "$as_me:$LINENO: checking for TIFFGetTagListCount in -ltiff" >&5
+if test "${ac_cv_header_tiff_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for tiff.h" >&5
+echo $ECHO_N "checking for tiff.h... $ECHO_C" >&6
+if test "${ac_cv_header_tiff_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_tiff_h" >&5
+echo "${ECHO_T}$ac_cv_header_tiff_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking tiff.h usability" >&5
+echo $ECHO_N "checking tiff.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <tiff.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking tiff.h presence" >&5
+echo $ECHO_N "checking tiff.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <tiff.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: tiff.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: tiff.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: tiff.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: tiff.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: tiff.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: tiff.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: tiff.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: tiff.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: tiff.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: tiff.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: tiff.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for tiff.h" >&5
+echo $ECHO_N "checking for tiff.h... $ECHO_C" >&6
+if test "${ac_cv_header_tiff_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_tiff_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_tiff_h" >&5
+echo "${ECHO_T}$ac_cv_header_tiff_h" >&6
+
+fi
+if test $ac_cv_header_tiff_h = yes; then
+  echo "$as_me:$LINENO: checking for TIFFGetTagListCount in -ltiff" >&5
 echo $ECHO_N "checking for TIFFGetTagListCount in -ltiff... $ECHO_C" >&6
 if test "${ac_cv_lib_tiff_TIFFGetTagListCount+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -4015,6 +4153,11 @@ if test $ac_cv_lib_tiff_TIFFGetTagListCount = yes; then
 else
   have_tiff="no"
 fi
+
+else
+  have_tiff="no"
+fi
+
 
 if test "$sys" = "win32" ; then
   have_tiff="no"
@@ -4113,7 +4256,145 @@ fi
 
 
 #### libgeotiff check ####
-echo "$as_me:$LINENO: checking for main in -lgeotiff" >&5
+if test "${ac_cv_header_geotiff_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for geotiff.h" >&5
+echo $ECHO_N "checking for geotiff.h... $ECHO_C" >&6
+if test "${ac_cv_header_geotiff_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_geotiff_h" >&5
+echo "${ECHO_T}$ac_cv_header_geotiff_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking geotiff.h usability" >&5
+echo $ECHO_N "checking geotiff.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <geotiff.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking geotiff.h presence" >&5
+echo $ECHO_N "checking geotiff.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <geotiff.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: geotiff.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: geotiff.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: geotiff.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: geotiff.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: geotiff.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: geotiff.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: geotiff.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: geotiff.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: geotiff.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: geotiff.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: geotiff.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: geotiff.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: geotiff.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: geotiff.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: geotiff.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: geotiff.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for geotiff.h" >&5
+echo $ECHO_N "checking for geotiff.h... $ECHO_C" >&6
+if test "${ac_cv_header_geotiff_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_geotiff_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_geotiff_h" >&5
+echo "${ECHO_T}$ac_cv_header_geotiff_h" >&6
+
+fi
+if test $ac_cv_header_geotiff_h = yes; then
+  echo "$as_me:$LINENO: checking for main in -lgeotiff" >&5
 echo $ECHO_N "checking for main in -lgeotiff... $ECHO_C" >&6
 if test "${ac_cv_lib_geotiff_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -4176,6 +4457,11 @@ if test $ac_cv_lib_geotiff_main = yes; then
 else
   have_geotiff="no"
 fi
+
+else
+  have_geotiff="no"
+fi
+
 
 if test "$sys" = "win32" ; then
   have_geotiff="no"
