Adding libpng.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PACKAGE VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LEX LEXLIB LEX_OUTPUT_ROOT YACC sys CPP EGREP ASF_LIB_GSL ASF_LIB_PROJ PKG_CONFIG ac_pt_PKG_CONFIG GLIB_CFLAGS GLIB_LIBS ASF_GLIB ASF_LIB_JPEG ASF_LIB_TIFF LIBTIFF_LOCATION ASF_LIB_GEOTIFF ASF_LIB_SHAPELIB ASF_LIB_FFTW ASF_LIB_TCL_TK GTK_CFLAGS GTK_LIBS LIBGLADE_CFLAGS LIBGLADE_LIBS ASF_GUI SHAREDIR BINDIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PACKAGE VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LEX LEXLIB LEX_OUTPUT_ROOT YACC sys CPP EGREP ASF_LIB_GSL ASF_LIB_PROJ PKG_CONFIG ac_pt_PKG_CONFIG GLIB_CFLAGS GLIB_LIBS ASF_GLIB ASF_LIB_JPEG ASF_LIB_TIFF LIBTIFF_LOCATION ASF_LIB_PNG ASF_LIB_GEOTIFF ASF_LIB_SHAPELIB ASF_LIB_FFTW ASF_LIB_TCL_TK GTK_CFLAGS GTK_LIBS LIBGLADE_CFLAGS LIBGLADE_LIBS ASF_GUI SHAREDIR BINDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1360,6 +1360,7 @@ have_shp="no"
 try_gtk="yes"
 have_gtk="no"
 have_fftw="no"
+have_png="no"
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -3956,6 +3957,88 @@ fi
 
 
 
+#### libpng check ####
+echo "$as_me:$LINENO: checking for png_write_image in -lpng" >&5
+echo $ECHO_N "checking for png_write_image in -lpng... $ECHO_C" >&6
+if test "${ac_cv_lib_png_png_write_image+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpng  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char png_write_image ();
+int
+main ()
+{
+png_write_image ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_png_png_write_image=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_png_png_write_image=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_png_png_write_image" >&5
+echo "${ECHO_T}$ac_cv_lib_png_png_write_image" >&6
+if test $ac_cv_lib_png_png_write_image = yes; then
+  have_png="yes"
+else
+  have_png="no"
+fi
+
+if test "$sys" = "win32" ; then
+   have_png="no"
+fi
+if test "$have_png" = "no" ; then
+   ASF_LIB_PNG="${ext_lib_src_dir}/libpng"
+   PNG_LIBS="\$(LIBDIR)/libpng.a"
+else
+   PNG_LIBS="-lpng"
+fi
+
+
 #### libgeotiff check ####
 echo "$as_me:$LINENO: checking for main in -lgeotiff" >&5
 echo $ECHO_N "checking for main in -lgeotiff... $ECHO_C" >&6
@@ -4506,6 +4589,9 @@ JPEG_CFLAGS = $JPEG_CFLAGS
 
 TIFF_LIBS = $TIFF_LIBS
 TIFF_CFLAGS = $TIFF_CFLAGS
+
+PNG_LIBS = $PNG_LIBS
+PNG_CFLAGS = $PNG_CFLAGS
 
 FFT_LIBS = $FFTW_LIBS
 FFT_CLFAGS = $FFTW_CFLAGS
@@ -5231,6 +5317,7 @@ s,@ASF_GLIB@,$ASF_GLIB,;t t
 s,@ASF_LIB_JPEG@,$ASF_LIB_JPEG,;t t
 s,@ASF_LIB_TIFF@,$ASF_LIB_TIFF,;t t
 s,@LIBTIFF_LOCATION@,$LIBTIFF_LOCATION,;t t
+s,@ASF_LIB_PNG@,$ASF_LIB_PNG,;t t
 s,@ASF_LIB_GEOTIFF@,$ASF_LIB_GEOTIFF,;t t
 s,@ASF_LIB_SHAPELIB@,$ASF_LIB_SHAPELIB,;t t
 s,@ASF_LIB_FFTW@,$ASF_LIB_FFTW,;t t
