Change the FFTW detection code to use the same method as the other libraries.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3738,7 +3738,76 @@ fi
 
 
 #### libjpeg check ####
-#AC_CHECK_LIB(jpeg,jinit_c_codec,have_jpeg="yes",have_jpeg="no")
+echo "$as_me:$LINENO: checking for jinit_c_codec in -ljpeg" >&5
+echo $ECHO_N "checking for jinit_c_codec in -ljpeg... $ECHO_C" >&6
+if test "${ac_cv_lib_jpeg_jinit_c_codec+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ljpeg  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char jinit_c_codec ();
+int
+main ()
+{
+jinit_c_codec ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_jpeg_jinit_c_codec=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_jpeg_jinit_c_codec=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_jpeg_jinit_c_codec" >&5
+echo "${ECHO_T}$ac_cv_lib_jpeg_jinit_c_codec" >&6
+if test $ac_cv_lib_jpeg_jinit_c_codec = yes; then
+  have_jpeg="yes"
+else
+  have_jpeg="no"
+fi
+
 if test "$have_jpeg" = "no" ; then
    ASF_LIB_JPEG="${ext_lib_src_dir}/libjpeg"
    JPEG_LIBS="\$(LIBDIR)/libjpeg.a"
@@ -4042,7 +4111,7 @@ fi
 
 if test "$have_fftw" = "no" ; then
    ASF_LIB_FFTW="${ext_lib_src_dir}/libfftw"
-   FFTW_LIBS="\$(LIBDIR)/libfftw.a"
+   FFTW_LIBS="\$(LIBDIR)/libfftw3f.a"
 else
    FFTW_LIBS="-lfftw"
 fi
@@ -4487,6 +4556,9 @@ JPEG_CFLAGS = $JPEG_CFLAGS
 TIFF_LIBS = $TIFF_LIBS
 TIFF_CFLAGS = $TIFF_CFLAGS
 
+FFT_LIBS = $FFTW_LIBS
+FFT_CLFAGS = $FFTW_CFLAGS
+
 GEOTIFF_LIBS = $GEOTIFF_LIBS
 GEOTIFF_CFLAGS = $GEOTIFF_CFLAGS
 
@@ -4500,9 +4572,6 @@ EOF
 
 # 'EOF' (with quotes) makes cat print out literal strings (no expanded variables [$])
 cat <<'EOF' >>system_rules
-
-FFT_LIBS = $(LIBDIR)/libfftw3f.a
-FFT_CLFAGS =
 
 CFLAGS  := $(CFLAGS) $(FLAGS) $(DEBUGFLAGS)
 LDFLAGS := $(LDFLAGS) $(DEBUGLIBS) -lm
